# Generated by Django 4.2.20 on 2025-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_id', models.CharField(max_length=20)),
                ('notify_date', models.DateField()),
                ('notify_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'fund_notification',
                'verbose_name_plural': 'fund_notification',
            },
        ),
        migrations.AddConstraint(
            model_name='fundnotification',
            constraint=models.UniqueConstraint(fields=('fund_id', 'notify_date'), name='unique_fund_notification'),
        ),
    ]
